# Generated by Django 4.1.3 on 2022-12-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='total_like_count',
            field=models.IntegerField(default=0),
        ),
    ]
